### PR TITLE
Update Kiota API to 26.0.5

### PR DESCRIPTION
**Pull request by Persistent13**
closes: #148

### CODE REVIEW

**Comment by Persistent13** [comment]
image

Nice!

@NikiforovAll Let me know if there's anything disagreeable in this PR and I'll do my best to correct.

**Comment by NikiforovAll** [comment]
@Persistent13 Could you please update the version of the Kitoa package manually?

**Comment by NikiforovAll** [comment]
Also, kiota CLI has been installed as `dotnet-tool`, could you please update id and try to regenerate to make sure we use the same version of Kiota CLI

**Comment by NikiforovAll** [comment]
Also, please make changes from https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/pull/148 to this PR

**Comment by NikiforovAll** [comment]
First and foremost, thank you for the contribution

**Comment by Persistent13** [comment]
@NikiforovAll I've updated the kiota versions and re-ran the generation command. I used 1.14.0 as that was newer, if you'd like me to use 1.13.1 explicitly, please let me know.

I updated the nuget package version to 26.0.5.

Please let me know if there's anything else.

**Comment by NikiforovAll** [comment]
Thank you for your contribution. Did you run `dotnet tool restore` in the root of the directory? I think we have kiota 1.15 installed as a local dotnet tool. Could you please update the version of the local dotnet tool and re-run the generation? 

```bash
dotnet tool install --local Microsoft.OpenApi.Kiota --version 1.20.0
````

Also, it would be great to test the generated SDK manually to make sure everything works. What do you think?

**Comment by Persistent13** [comment]
Yes, I did run it with the cached version. Apologies!

I think the new push should have corrected this. I won't be able to test it my time tonight, but I should be able to tomorrow. I'll update with my findings then.

**Comment by NikiforovAll** [comment]
I appreciate your work!

**Comment by Persistent13** [comment]
@NikiforovAll Sorry for the delay, I had some stuff that took my time away from this.

From what I can see, it all works fine. I tried out the newer organization APIs as well and didn't run into any issues. I could create and delete orgs without issue after enabling the feature for a given realm.

**Pull request merged**
