### PR TITLE
feat: Add JoinGroup and LeaveGroup endpoints

### PR DESCRIPTION
**Pull request by InChh**
Add JoinGroup and LeaveGroup endpoints to IKeycloakUserClient.

### CODE REVIEW

**Comment by drlivsi** [comment]
A useful improvement since we currently cannot manage user groups.

**Comment by NikiforovAll** [comment]
I plan to resolve it via #46

**Comment by NikiforovAll** [comment]
Plan to use automatically generated clients based on OpenAPI Spec. This ticket is not needed. Thank you for the contribution

**Comment by NikiforovAll** [comment]
Will be added to 2.0.0 release as separate PR

**Pull request closed without merging**
