### PR TITLE
feat: update kiota api to 25.0.2

### PR DESCRIPTION
**Pull request by Persistent13**
This updates the Kiota package to the 25.0.2 release of Keycloak.

I think this is all good but please let me know if you need anything else from me!

### CODE REVIEW

**Comment by Persistent13** [comment]
I'm going to investigate the src/Directory.Packages.props conflict.

Are the other conflicts of issue? I'd think not since they're generated but I'm not sure if that's due to something being generated incorrectly.

**Comment by Persistent13** [comment]
I figured it out, I had an outdated main. I'll rebase and push the changes.

**Comment by NikiforovAll** [comment]
Can we somehow reduce the number of changes? I remember pinning the Kiota tool version that should be used for generations to avoid these massive changes. Could you please provide a version of the kiota tool that was used for the process of generation?

**Comment by Persistent13** [comment]
> Can we somehow reduce the number of changes? I remember pinning the Kiota tool version that should be used for generations to avoid these massive changes. Could you please provide a version of the kiota tool that was used for the process of generation?

It was 1.16.0 to build this and the prior version according to the lock file was 1.15.0.

I'll downgrade, rerun this, and push the changes.

**Comment by Persistent13** [comment]
Follow up on this, my goal here was to bring in the organization APIs since those are new for 25 and I just assumed that 25.0.0 didn't have them for whatever reason but it turns out they're just plain missing from the openapi definition file at this moment. https://github.com/keycloak/keycloak/issues/30832

Once that's addressed, I'll update this PR. Until then I'll put it in a draft state but if that's undesirable for you, feel free to close it and I can always reopen it.

**Comment by xXAvoraXx** [comment]
It would be great if after creating a Role or Group, the ID of the created entity could be returned. @Persistent13 

https://github.com/keycloak/keycloak/discussions/32027

**Comment by Persistent13** [comment]
Closing in favor of #154

**Pull request closed without merging**
