### PR TITLE
Update samples dependencies

### PR DESCRIPTION
**Pull request by bdovaz**
There are many of them that had severe vulnerabilities.

Small formatting problems or problems with certain analyzers have also been fixed.

### CODE REVIEW

**Comment by bdovaz** [comment]
@NikiforovAll please merge, thanks!

**Comment by NikiforovAll** [comment]
Thank you for the contribution, I will take a look.

**Comment by NikiforovAll** [comment]
Could you please specify what kind of analyzers did you use to make the changes?

**Comment by bdovaz** [comment]
Dependency track and Visual Studio IDE (reports vulnerable packages)

**Comment by bdovaz** [comment]
@NikiforovAll can you merge and release a new version please? Thanks!

**Comment by NikiforovAll** [comment]
@bdovaz Sorry for the delayed response, I plan to work on 2.0.0 and include your code in release. Also, there are other changes with HTTP client management that I want to change so it might take some time.

**Comment by bdovaz** [comment]
Okay, if you need help to solve it faster, let me know.

**Comment by PaulARoy** [comment]
Hi @NikiforovAll, would it be possible to integrate this in a patch or alpha version before your 2.0.0?

This is preventing us from upgrading other frameworks and has severe vulnerabilities, if 2.0.0 take some time (no pressure for this!) it would be best to address this early — even if it's just an alpha version with no support.

**Comment by bdovaz** [comment]
Same problem here...

**Comment by NikiforovAll** [comment]
OK, will do

cc: @bdovaz, @PaulARoy

**Comment by NikiforovAll** [comment]
Added 1.7.0 version, could you please take a look? it would be great if you update dependencies for sample projects in a separate PR

**Comment by bdovaz** [comment]
@NikiforovAll I have converted this PR into a PR that only updates dependencies of the examples so it is ready for your review.

As you can see I have unified in the *.props files the same as `src` to make it easier to manage.

**Comment by NikiforovAll** [comment]
LGTM, thank you for the contribution, @bdovaz

**Comment by NikiforovAll** [comment]
@bdovaz could you please take a look at the build? it fails because of changes in package management

**Comment by bdovaz** [comment]
@NikiforovAll I think I have already solved it, it is that the `MinimalApiDependsOnNuGetSource` project is a bit special because it references NuGet's own published packages, in the end I have disabled `ManagePackageVersionsCentrally` in that particular case.

**Pull request merged**
