### PR TITLE
Fixed relative address construction

### PR DESCRIPTION
**Pull request by juan-dev-santos**
(This is my first pull request so any feedback on how to improve is welcomed)

I have changed the initial '/' in ApiUrls that was avoiding correct relative uri construction and also added a test to verify it is working

### CODE REVIEW

**Comment by NikiforovAll** [comment]
Hi @juan-dev-santos, could you please rebase onto the main?

**Comment by juan-dev-santos** [comment]
> Hi @juan-dev-santos, could you please rebase onto the main?

Sorry but how should I do it?

This is the first time contributing

**Comment by juan-dev-santos** [comment]
I have merged last changes into my fork and sent a PR again
Is this what you were asking me?

**Comment by NikiforovAll** [comment]
@juan-dev-santos thank you for the contribution! I will include it in the next release - `2.5.4`

**Comment by juan-dev-santos** [comment]
> @juan-dev-santos thank you for the contribution! I will include it in the next release - `2.5.4`

Thanks! Glad I could help

**Comment by taufikdev88** [comment]
Hello, can you do retest for this PR, because this PR caused the Admin-Http-Client on Keycloak.AuthServices.Sdk does not build correct ApiUrls path

generated url is: /realms/{realm}/admin/realms/{realm}/groups

expected: /admin/realms/{realm}/groups

image

**Comment by taufikdev88** [comment]
maybe just replace base url using keycloak-auth-url only without realm will solved the issue ? 
image

**Comment by NikiforovAll** [comment]
Oh wow, let's rollback

**Pull request merged**
