### PR TITLE
Update Kiota SDK to Keycloak 25.0.0.

### PR DESCRIPTION
**Pull request by kanpov**

### CODE REVIEW

**Comment by NikiforovAll** [comment]
@kanpov  could you please run `csharpier` for generated code (see dotent-tool manifest file for more details). the goal is to have less diffs

**Comment by kanpov** [comment]
> @kanpov could you please run `csharpier` for generated code (see dotent-tool manifest file for more details). the goal is to have less diffs

I ran `dotnet csharpier .` on the Kiota SDK project and it changed nothing, at least as far as `git status` tells me.

**Comment by NikiforovAll** [comment]
Could you please run `dotnet tool install Microsoft.OpenApi.Kiota` in the root of the project and add the changes? I want to pin the version of kiota essentially :)

**Comment by kanpov** [comment]
> Could you please run `dotnet tool install Microsoft.OpenApi.Kiota` in the root of the project and add the changes? I want to pin the version of kiota essentially :)

Done

**Comment by kanpov** [comment]
image
Why this is happening I have no idea to be honest.

**Comment by NikiforovAll** [comment]
Thank you for the contribution, the changes will be deployed as part of `2.5.2` release

**Pull request merged**
